/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Array = number[];

export interface Example {
  id?: number;
  data?: Array;
  struct?: {
    a?: unknown;
  };
  address?: Address;
  [k: string]: unknown;
}
export interface Address {
  street_address?: string;
  city?: string;
  state?: string;
}
